<?php

// Data functions (insert, update, delete, form) for table medical_records

// This script and data application were generated by AppGini 5.62
// Download AppGini for free from https://bigprof.com/appgini/download/

function medical_records_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('medical_records');
	if(!$arrPerm[1]){
		return false;
	}

	$data['description'] = br2nl(makeSafe($_REQUEST['description']));
	$data['image_1'] = PrepareUploadedFile('image_1', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image_1']) createThumbnail($data['image_1'], getThumbnailSpecs('medical_records', 'image_1', 'tv'));
	if($data['image_1']) createThumbnail($data['image_1'], getThumbnailSpecs('medical_records', 'image_1', 'dv'));
	$data['image_2'] = PrepareUploadedFile('image_2', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image_2']) createThumbnail($data['image_2'], getThumbnailSpecs('medical_records', 'image_2', 'tv'));
	if($data['image_2']) createThumbnail($data['image_2'], getThumbnailSpecs('medical_records', 'image_2', 'dv'));
	$data['image_3'] = PrepareUploadedFile('image_3', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image_3']) createThumbnail($data['image_3'], getThumbnailSpecs('medical_records', 'image_3', 'tv'));
	if($data['image_3']) createThumbnail($data['image_3'], getThumbnailSpecs('medical_records', 'image_3', 'dv'));
	$data['image_4'] = PrepareUploadedFile('image_4', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image_4']) createThumbnail($data['image_4'], getThumbnailSpecs('medical_records', 'image_4', 'tv'));
	if($data['image_4']) createThumbnail($data['image_4'], getThumbnailSpecs('medical_records', 'image_4', 'dv'));
	$data['image_5'] = PrepareUploadedFile('image_5', 1024000,'jpg|jpeg|gif|png', false, '');
	if($data['image_5']) createThumbnail($data['image_5'], getThumbnailSpecs('medical_records', 'image_5', 'tv'));
	if($data['image_5']) createThumbnail($data['image_5'], getThumbnailSpecs('medical_records', 'image_5', 'dv'));
	$data['document_1'] = PrepareUploadedFile('document_1', 5120000,'txt|doc|docx|docm|odt|pdf|rtf', false, '');
	$data['document_2'] = PrepareUploadedFile('document_2', 5120000,'txt|doc|docx|docm|odt|pdf|rtf', false, '');
	$data['document_3'] = PrepareUploadedFile('document_3', 5120000,'txt|doc|docx|docm|odt|pdf|rtf', false, '');
	$data['document_4'] = PrepareUploadedFile('document_4', 5120000,'txt|doc|docx|docm|odt|pdf|rtf', false, '');
	$data['document_5'] = PrepareUploadedFile('document_5', 5120000,'txt|doc|docx|docm|odt|pdf|rtf', false, '');

	/* for empty upload fields, when saving a copy of an existing record, copy the original upload field */
	if($_REQUEST['SelectedID']){
		$res = sql("select * from medical_records where id='" . makeSafe($_REQUEST['SelectedID']) . "'", $eo);
		if($row = db_fetch_assoc($res)){
			if(!$data['image_1']) $data['image_1'] = makeSafe($row['image_1']);
			if(!$data['image_2']) $data['image_2'] = makeSafe($row['image_2']);
			if(!$data['image_3']) $data['image_3'] = makeSafe($row['image_3']);
			if(!$data['image_4']) $data['image_4'] = makeSafe($row['image_4']);
			if(!$data['image_5']) $data['image_5'] = makeSafe($row['image_5']);
			if(!$data['document_1']) $data['document_1'] = makeSafe($row['document_1']);
			if(!$data['document_2']) $data['document_2'] = makeSafe($row['document_2']);
			if(!$data['document_3']) $data['document_3'] = makeSafe($row['document_3']);
			if(!$data['document_4']) $data['document_4'] = makeSafe($row['document_4']);
			if(!$data['document_5']) $data['document_5'] = makeSafe($row['document_5']);
		}
	}

	// hook: medical_records_before_insert
	if(function_exists('medical_records_before_insert')){
		$args=array();
		if(!medical_records_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `medical_records` set       ' . ($data['image_1'] != '' ? "`image_1`='{$data['image_1']}'" : '`image_1`=NULL') . ', ' . ($data['image_2'] != '' ? "`image_2`='{$data['image_2']}'" : '`image_2`=NULL') . ', ' . ($data['image_3'] != '' ? "`image_3`='{$data['image_3']}'" : '`image_3`=NULL') . ', ' . ($data['image_4'] != '' ? "`image_4`='{$data['image_4']}'" : '`image_4`=NULL') . ', ' . ($data['image_5'] != '' ? "`image_5`='{$data['image_5']}'" : '`image_5`=NULL') . ', ' . ($data['document_1'] != '' ? "`document_1`='{$data['document_1']}'" : '`document_1`=NULL') . ', ' . ($data['document_2'] != '' ? "`document_2`='{$data['document_2']}'" : '`document_2`=NULL') . ', ' . ($data['document_3'] != '' ? "`document_3`='{$data['document_3']}'" : '`document_3`=NULL') . ', ' . ($data['document_4'] != '' ? "`document_4`='{$data['document_4']}'" : '`document_4`=NULL') . ', ' . ($data['document_5'] != '' ? "`document_5`='{$data['document_5']}'" : '`document_5`=NULL') . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"medical_records_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// automatic patient
	if($_REQUEST['filterer_patient']){
		sql("update `medical_records` set `patient`='" . makeSafe($_REQUEST['filterer_patient']) . "' where `id`='" . makeSafe($recID, false) . "'", $eo);
	}

	// hook: medical_records_after_insert
	if(function_exists('medical_records_after_insert')){
		$res = sql("select * from `medical_records` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!medical_records_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	sql("insert ignore into membership_userrecords set tableName='medical_records', pkValue='" . makeSafe($recID, false) . "', memberID='" . makeSafe(getLoggedMemberID(), false) . "', dateAdded='" . time() . "', dateUpdated='" . time() . "', groupID='" . getLoggedGroupID() . "'", $eo);

	return $recID;
}

function medical_records_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('medical_records');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='medical_records' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='medical_records' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: medical_records_before_delete
	if(function_exists('medical_records_before_delete')){
		$args=array();
		if(!medical_records_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `medical_records` where `id`='$selected_id'", $eo);

	// hook: medical_records_after_delete
	if(function_exists('medical_records_after_delete')){
		$args=array();
		medical_records_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='medical_records' and pkValue='$selected_id'", $eo);
}

function medical_records_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('medical_records');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='medical_records' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='medical_records' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['description'] = br2nl(makeSafe($_REQUEST['description']));
	$data['selectedID']=makeSafe($selected_id);
	if($_REQUEST['image_1_remove'] == 1){
		$data['image_1'] = '';
	}else{
		$data['image_1'] = PrepareUploadedFile('image_1', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image_1']) createThumbnail($data['image_1'], getThumbnailSpecs('medical_records', 'image_1', 'tv'));
		if($data['image_1']) createThumbnail($data['image_1'], getThumbnailSpecs('medical_records', 'image_1', 'dv'));
	}
	if($_REQUEST['image_2_remove'] == 1){
		$data['image_2'] = '';
	}else{
		$data['image_2'] = PrepareUploadedFile('image_2', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image_2']) createThumbnail($data['image_2'], getThumbnailSpecs('medical_records', 'image_2', 'tv'));
		if($data['image_2']) createThumbnail($data['image_2'], getThumbnailSpecs('medical_records', 'image_2', 'dv'));
	}
	if($_REQUEST['image_3_remove'] == 1){
		$data['image_3'] = '';
	}else{
		$data['image_3'] = PrepareUploadedFile('image_3', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image_3']) createThumbnail($data['image_3'], getThumbnailSpecs('medical_records', 'image_3', 'tv'));
		if($data['image_3']) createThumbnail($data['image_3'], getThumbnailSpecs('medical_records', 'image_3', 'dv'));
	}
	if($_REQUEST['image_4_remove'] == 1){
		$data['image_4'] = '';
	}else{
		$data['image_4'] = PrepareUploadedFile('image_4', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image_4']) createThumbnail($data['image_4'], getThumbnailSpecs('medical_records', 'image_4', 'tv'));
		if($data['image_4']) createThumbnail($data['image_4'], getThumbnailSpecs('medical_records', 'image_4', 'dv'));
	}
	if($_REQUEST['image_5_remove'] == 1){
		$data['image_5'] = '';
	}else{
		$data['image_5'] = PrepareUploadedFile('image_5', 1024000, 'jpg|jpeg|gif|png', false, "");
		if($data['image_5']) createThumbnail($data['image_5'], getThumbnailSpecs('medical_records', 'image_5', 'tv'));
		if($data['image_5']) createThumbnail($data['image_5'], getThumbnailSpecs('medical_records', 'image_5', 'dv'));
	}
	if($_REQUEST['document_1_remove'] == 1){
		$data['document_1'] = '';
	}else{
		$data['document_1'] = PrepareUploadedFile('document_1', 5120000, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
	}
	if($_REQUEST['document_2_remove'] == 1){
		$data['document_2'] = '';
	}else{
		$data['document_2'] = PrepareUploadedFile('document_2', 5120000, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
	}
	if($_REQUEST['document_3_remove'] == 1){
		$data['document_3'] = '';
	}else{
		$data['document_3'] = PrepareUploadedFile('document_3', 5120000, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
	}
	if($_REQUEST['document_4_remove'] == 1){
		$data['document_4'] = '';
	}else{
		$data['document_4'] = PrepareUploadedFile('document_4', 5120000, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
	}
	if($_REQUEST['document_5_remove'] == 1){
		$data['document_5'] = '';
	}else{
		$data['document_5'] = PrepareUploadedFile('document_5', 5120000, 'txt|doc|docx|docm|odt|pdf|rtf', false, "");
	}

	// hook: medical_records_before_update
	if(function_exists('medical_records_before_update')){
		$args=array();
		if(!medical_records_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `medical_records` set       ' . ($data['image_1']!='' ? "`image_1`='{$data['image_1']}'" : ($_REQUEST['image_1_remove'] != 1 ? '`image_1`=`image_1`' : '`image_1`=NULL')) . ', ' . ($data['image_2']!='' ? "`image_2`='{$data['image_2']}'" : ($_REQUEST['image_2_remove'] != 1 ? '`image_2`=`image_2`' : '`image_2`=NULL')) . ', ' . ($data['image_3']!='' ? "`image_3`='{$data['image_3']}'" : ($_REQUEST['image_3_remove'] != 1 ? '`image_3`=`image_3`' : '`image_3`=NULL')) . ', ' . ($data['image_4']!='' ? "`image_4`='{$data['image_4']}'" : ($_REQUEST['image_4_remove'] != 1 ? '`image_4`=`image_4`' : '`image_4`=NULL')) . ', ' . ($data['image_5']!='' ? "`image_5`='{$data['image_5']}'" : ($_REQUEST['image_5_remove'] != 1 ? '`image_5`=`image_5`' : '`image_5`=NULL')) . ', ' . ($data['document_1']!='' ? "`document_1`='{$data['document_1']}'" : ($_REQUEST['document_1_remove'] != 1 ? '`document_1`=`document_1`' : '`document_1`=NULL')) . ', ' . ($data['document_2']!='' ? "`document_2`='{$data['document_2']}'" : ($_REQUEST['document_2_remove'] != 1 ? '`document_2`=`document_2`' : '`document_2`=NULL')) . ', ' . ($data['document_3']!='' ? "`document_3`='{$data['document_3']}'" : ($_REQUEST['document_3_remove'] != 1 ? '`document_3`=`document_3`' : '`document_3`=NULL')) . ', ' . ($data['document_4']!='' ? "`document_4`='{$data['document_4']}'" : ($_REQUEST['document_4_remove'] != 1 ? '`document_4`=`document_4`' : '`document_4`=NULL')) . ', ' . ($data['document_5']!='' ? "`document_5`='{$data['document_5']}'" : ($_REQUEST['document_5_remove'] != 1 ? '`document_5`=`document_5`' : '`document_5`=NULL')) . ', `description`=' . (($data['description'] !== '' && $data['description'] !== NULL) ? "'{$data['description']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="medical_records_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: medical_records_after_update
	if(function_exists('medical_records_after_update')){
		$res = sql("SELECT * FROM `medical_records` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!medical_records_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='medical_records' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function medical_records_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('medical_records');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_patient = thisOr(undo_magic_quotes($_REQUEST['filterer_patient']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: patient
	$combo_patient = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='medical_records' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='medical_records' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `medical_records` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'medical_records_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_patient->SelectedData = $row['patient'];
	}else{
		$combo_patient->SelectedData = $filterer_patient;
	}
	$combo_patient->HTML = '<span id="patient-container' . $rnd1 . '"></span><input type="hidden" name="patient" id="patient' . $rnd1 . '" value="' . html_attr($combo_patient->SelectedData) . '">';
	$combo_patient->MatchText = '<span id="patient-container-readonly' . $rnd1 . '"></span><input type="hidden" name="patient" id="patient' . $rnd1 . '" value="' . html_attr($combo_patient->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_patient__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['patient'] : $filterer_patient); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(patient_reload__RAND__) == 'function') patient_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function patient_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#patient-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_patient__RAND__.value, t: 'medical_records', f: 'patient' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="patient"]').val(resp.results[0].id);
							$j('[id=patient-container-readonly__RAND__]').html('<span id="patient-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=patients_view_parent]').hide(); }else{ $j('.btn[id=patients_view_parent]').show(); }


							if(typeof(patient_update_autofills__RAND__) == 'function') patient_update_autofills__RAND__();
						}
					});
				},
				width: ($j('fieldset .col-xs-11').width() - select2_max_width_decrement()) + 'px',
				formatNoMatches: function(term){ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 10,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ return { s: term, p: page, t: 'medical_records', f: 'patient' }; },
					results: function(resp, page){ return resp; }
				},
				escapeMarkup: function(str){ return str; }
			}).on('change', function(e){
				AppGini.current_patient__RAND__.value = e.added.id;
				AppGini.current_patient__RAND__.text = e.added.text;
				$j('[name="patient"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=patients_view_parent]').hide(); }else{ $j('.btn[id=patients_view_parent]').show(); }


				if(typeof(patient_update_autofills__RAND__) == 'function') patient_update_autofills__RAND__();
			});

			if(!$j("#patient-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_patient__RAND__.value, t: 'medical_records', f: 'patient' },
					success: function(resp){
						$j('[name="patient"]').val(resp.results[0].id);
						$j('[id=patient-container-readonly__RAND__]').html('<span id="patient-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=patients_view_parent]').hide(); }else{ $j('.btn[id=patients_view_parent]').show(); }

						if(typeof(patient_update_autofills__RAND__) == 'function') patient_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_patient__RAND__.value, t: 'medical_records', f: 'patient' },
				success: function(resp){
					$j('[id=patient-container__RAND__], [id=patient-container-readonly__RAND__]').html('<span id="patient-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=patients_view_parent]').hide(); }else{ $j('.btn[id=patients_view_parent]').show(); }

					if(typeof(patient_update_autofills__RAND__) == 'function') patient_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/medical_records_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/medical_records_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Datos del documento del paciente', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return medical_records_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return medical_records_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'window.parent.jQuery(\'.modal\').modal(\'hide\'); return false;';
	}else{
		$backAction = '$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode=str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$$(\'form\')[0].writeAttribute(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return medical_records_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode=str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode=str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#image_1').replaceWith('<div class=\"form-control-static\" id=\"image_1\">' + (jQuery('#image_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#image_2').replaceWith('<div class=\"form-control-static\" id=\"image_2\">' + (jQuery('#image_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#image_3').replaceWith('<div class=\"form-control-static\" id=\"image_3\">' + (jQuery('#image_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#image_4').replaceWith('<div class=\"form-control-static\" id=\"image_4\">' + (jQuery('#image_4').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#image_5').replaceWith('<div class=\"form-control-static\" id=\"image_5\">' + (jQuery('#image_5').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#document_1').replaceWith('<div class=\"form-control-static\" id=\"document_1\">' + (jQuery('#document_1').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#document_2').replaceWith('<div class=\"form-control-static\" id=\"document_2\">' + (jQuery('#document_2').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#document_3').replaceWith('<div class=\"form-control-static\" id=\"document_3\">' + (jQuery('#document_3').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#document_4').replaceWith('<div class=\"form-control-static\" id=\"document_4\">' + (jQuery('#document_4').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#document_5').replaceWith('<div class=\"form-control-static\" id=\"document_5\">' + (jQuery('#document_5').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#description').replaceWith('<div class=\"form-control-static\" id=\"description\">' + (jQuery('#description').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode=str_replace('<%%COMBO(patient)%%>', $combo_patient->HTML, $templateCode);
	$templateCode=str_replace('<%%COMBOTEXT(patient)%%>', $combo_patient->MatchText, $templateCode);
	$templateCode=str_replace('<%%URLCOMBOTEXT(patient)%%>', urlencode($combo_patient->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'patient' => array('patients', 'Patient'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode=str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(patient)%%>', '', $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(image_1)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input type="file" name="image_1" id="image_1">'), $templateCode);
	if($AllowUpdate && $row['image_1']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image_1)%%>', '<br><input type="checkbox" name="image_1_remove" id="image_1_remove" value="1"> <label for="image_1_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image_1)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(image_2)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input type="file" name="image_2" id="image_2">'), $templateCode);
	if($AllowUpdate && $row['image_2']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image_2)%%>', '<br><input type="checkbox" name="image_2_remove" id="image_2_remove" value="1"> <label for="image_2_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image_2)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(image_3)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input type="file" name="image_3" id="image_3">'), $templateCode);
	if($AllowUpdate && $row['image_3']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image_3)%%>', '<br><input type="checkbox" name="image_3_remove" id="image_3_remove" value="1"> <label for="image_3_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image_3)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(image_4)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input type="file" name="image_4" id="image_4">'), $templateCode);
	if($AllowUpdate && $row['image_4']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image_4)%%>', '<br><input type="checkbox" name="image_4_remove" id="image_4_remove" value="1"> <label for="image_4_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image_4)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(image_5)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=1024000>'.$Translation['upload image'].' <input type="file" name="image_5" id="image_5">'), $templateCode);
	if($AllowUpdate && $row['image_5']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(image_5)%%>', '<br><input type="checkbox" name="image_5_remove" id="image_5_remove" value="1"> <label for="image_5_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(image_5)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(document_1)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5120000>'.$Translation['upload image'].' <input type="file" name="document_1" id="document_1">'), $templateCode);
	$templateCode=str_replace('<%%UPLOADFILE(document_2)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5120000>'.$Translation['upload image'].' <input type="file" name="document_2" id="document_2">'), $templateCode);
	if($AllowUpdate && $row['document_2']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(document_2)%%>', '<br><input type="checkbox" name="document_2_remove" id="document_2_remove" value="1"> <label for="document_2_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(document_2)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(document_3)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5120000>'.$Translation['upload image'].' <input type="file" name="document_3" id="document_3">'), $templateCode);
	if($AllowUpdate && $row['document_3']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(document_3)%%>', '<br><input type="checkbox" name="document_3_remove" id="document_3_remove" value="1"> <label for="document_3_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(document_3)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(document_4)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5120000>'.$Translation['upload image'].' <input type="file" name="document_4" id="document_4">'), $templateCode);
	if($AllowUpdate && $row['document_4']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(document_4)%%>', '<br><input type="checkbox" name="document_4_remove" id="document_4_remove" value="1"> <label for="document_4_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(document_4)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(document_5)%%>', ($noUploads ? '' : '<input type=hidden name=MAX_FILE_SIZE value=5120000>'.$Translation['upload image'].' <input type="file" name="document_5" id="document_5">'), $templateCode);
	if($AllowUpdate && $row['document_5']!=''){
		$templateCode=str_replace('<%%REMOVEFILE(document_5)%%>', '<br><input type="checkbox" name="document_5_remove" id="document_5_remove" value="1"> <label for="document_5_remove" style="color: red; font-weight: bold;">'.$Translation['remove image'].'</label>', $templateCode);
	}else{
		$templateCode=str_replace('<%%REMOVEFILE(document_5)%%>', '', $templateCode);
	}
	$templateCode=str_replace('<%%UPLOADFILE(description)%%>', '', $templateCode);

	// process values
	if($selected_id){
		$templateCode=str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode=str_replace('<%%VALUE(patient)%%>', html_attr($row['patient']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(patient)%%>', urlencode($urow['patient']), $templateCode);
		$row['image_1']=($row['image_1']!=''?$row['image_1']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(image_1)%%>', html_attr($row['image_1']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image_1)%%>', urlencode($urow['image_1']), $templateCode);
		$row['image_2']=($row['image_2']!=''?$row['image_2']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(image_2)%%>', html_attr($row['image_2']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image_2)%%>', urlencode($urow['image_2']), $templateCode);
		$row['image_3']=($row['image_3']!=''?$row['image_3']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(image_3)%%>', html_attr($row['image_3']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image_3)%%>', urlencode($urow['image_3']), $templateCode);
		$row['image_4']=($row['image_4']!=''?$row['image_4']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(image_4)%%>', html_attr($row['image_4']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image_4)%%>', urlencode($urow['image_4']), $templateCode);
		$row['image_5']=($row['image_5']!=''?$row['image_5']:'blank.gif');
		$templateCode=str_replace('<%%VALUE(image_5)%%>', html_attr($row['image_5']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(image_5)%%>', urlencode($urow['image_5']), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_1)%%>', html_attr($row['document_1']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_1)%%>', urlencode($urow['document_1']), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_2)%%>', html_attr($row['document_2']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_2)%%>', urlencode($urow['document_2']), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_3)%%>', html_attr($row['document_3']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_3)%%>', urlencode($urow['document_3']), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_4)%%>', html_attr($row['document_4']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_4)%%>', urlencode($urow['document_4']), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_5)%%>', html_attr($row['document_5']), $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_5)%%>', urlencode($urow['document_5']), $templateCode);
		if($dvprint){
			$templateCode = str_replace('<%%VALUE(description)%%>', nl2br(html_attr($row['description'])), $templateCode);
		}else{
			$templateCode = str_replace('<%%VALUE(description)%%>', html_attr($row['description']), $templateCode);
		}
		$templateCode=str_replace('<%%URLVALUE(description)%%>', urlencode($urow['description']), $templateCode);
	}else{
		$templateCode=str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(patient)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(patient)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(image_1)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(image_2)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(image_3)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(image_4)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(image_5)%%>', 'blank.gif', $templateCode);
		$templateCode=str_replace('<%%VALUE(document_1)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_1)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_2)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_2)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_3)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_3)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_4)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_4)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(document_5)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(document_5)%%>', urlencode(''), $templateCode);
		$templateCode=str_replace('<%%VALUE(description)%%>', '', $templateCode);
		$templateCode=str_replace('<%%URLVALUE(description)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode=str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode=str_replace('<%%', '<!-- ', $templateCode);
	$templateCode=str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields
	if( $_REQUEST['FilterField'][1]=='2' && $_REQUEST['FilterOperator'][1]=='<=>'){
		$templateCode.="\n<input type=hidden name=patient value=\"" . html_attr((get_magic_quotes_gpc() ? stripslashes($_REQUEST['FilterValue'][1]) : $_REQUEST['FilterValue'][1]))."\">\n";
	}

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('medical_records');
	if($selected_id){
		$jdata = get_joined_record('medical_records', $selected_id);
		$rdata = $row;
	}
	$cache_data = array(
		'rdata' => array_map('nl2br', array_map('addslashes', $rdata)),
		'jdata' => array_map('nl2br', array_map('addslashes', $jdata)),
	);
	$templateCode .= loadView('medical_records-ajax-cache', $cache_data);

	// hook: medical_records_dv
	if(function_exists('medical_records_dv')){
		$args=array();
		medical_records_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>